#!/bin/bash

rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
date

platypus-test --id-only

systemctl daemon-reload

echo "> enable autostart service with 'systemctl enable platypus'"

